/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Feb 27 18:45:54 GMT 2020
 */

package com.google.escapevelocity;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

@EvoSuiteClassExclude
public class MethodFinder_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.google.escapevelocity.MethodFinder"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/9c/2fm2fk412pj9zjkzvdx9w2fr0000gn/T/"); 
    java.lang.System.setProperty("user.country", "BR"); 
    java.lang.System.setProperty("user.dir", "/Users/joaocorreia/escapevelocity"); 
    java.lang.System.setProperty("user.home", "/Users/joaocorreia"); 
    java.lang.System.setProperty("user.language", "pt"); 
    java.lang.System.setProperty("user.name", "joaocorreia"); 
    java.lang.System.setProperty("user.timezone", "America/Sao_Paulo"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(MethodFinder_ESTest_scaffolding.class.getClassLoader() ,
      "com.google.common.collect.ImmutableSet$SetBuilderImpl",
      "com.google.common.collect.AllEqualOrdering",
      "com.google.common.math.IntMath$1",
      "com.google.common.collect.Hashing",
      "com.google.common.collect.ImmutableList$SubList",
      "com.google.common.collect.Lists$RandomAccessPartition",
      "com.google.common.collect.HashBasedTable",
      "com.google.common.collect.StandardTable$RowMap",
      "com.google.escapevelocity.StopNode$ElseIfNode",
      "com.google.common.collect.PeekingIterator",
      "com.google.common.collect.Maps$NavigableKeySet",
      "com.google.common.collect.RegularImmutableList",
      "com.google.common.collect.StandardTable$ColumnKeySet",
      "com.google.common.math.IntMath",
      "com.google.common.base.Optional",
      "com.google.common.collect.Lists$TransformingRandomAccessList",
      "com.google.common.collect.Iterators$ArrayItr",
      "com.google.escapevelocity.Node$Cons",
      "com.google.common.collect.Maps$KeySet",
      "com.google.common.collect.ImmutableMap$IteratorBasedImmutableMap$1EntrySetImpl",
      "com.google.common.collect.NullsLastOrdering",
      "com.google.escapevelocity.Node",
      "com.google.common.collect.ImmutableMapKeySet",
      "com.google.common.collect.Maps$Values",
      "com.google.common.collect.BaseImmutableMultimap",
      "com.google.escapevelocity.MethodFinder",
      "com.google.common.base.Converter$IdentityConverter",
      "com.google.common.collect.Range",
      "com.google.common.collect.Maps$SortedKeySet",
      "com.google.common.collect.StandardTable$TableSet",
      "com.google.common.collect.ByFunctionOrdering",
      "com.google.common.collect.SortedMapDifference",
      "com.google.common.collect.RegularImmutableSet",
      "com.google.common.collect.Iterators$10",
      "com.google.common.collect.ImmutableMap$IteratorBasedImmutableMap",
      "com.google.common.base.Predicate",
      "com.google.common.collect.LexicographicalOrdering",
      "com.google.common.collect.StandardTable$Row",
      "com.google.common.collect.Maps$AbstractFilteredMap",
      "com.google.escapevelocity.EvaluationContext",
      "com.google.common.collect.Iterators$ConcatenatedIterator",
      "com.google.common.collect.HashBasedTable$Factory",
      "com.google.common.collect.Iterables",
      "com.google.common.collect.NullsFirstOrdering",
      "com.google.common.collect.ImmutableAsList",
      "com.google.common.collect.ImmutableSet$Builder",
      "com.google.common.collect.RegularImmutableAsList",
      "com.google.common.collect.Maps$FilteredEntryMap",
      "com.google.common.collect.SingletonImmutableSet",
      "com.google.common.collect.ImmutableMapEntrySet",
      "com.google.common.collect.Lists$Partition",
      "com.google.common.collect.Lists",
      "com.google.common.math.MathPreconditions",
      "com.google.common.collect.UnmodifiableListIterator",
      "com.google.common.collect.UsingToStringOrdering",
      "com.google.common.collect.ImmutableMultimap",
      "com.google.common.collect.Maps$Accumulator",
      "com.google.common.collect.Lists$TransformingSequentialList",
      "com.google.common.collect.ImmutableSortedSet",
      "com.google.common.collect.RangeGwtSerializationDependencies",
      "com.google.common.collect.ObjectArrays",
      "com.google.common.collect.Maps$BiMapConverter",
      "com.google.common.collect.AbstractIterator",
      "com.google.common.collect.ImmutableSortedSet$Builder",
      "com.google.common.collect.ImmutableList$1",
      "com.google.common.collect.MapDifference",
      "com.google.common.collect.ImmutableMap$MapViewOfValuesAsSingletonSets",
      "com.google.common.collect.SortedIterable",
      "com.google.common.collect.StandardTable",
      "com.google.common.collect.Sets$ImprovedAbstractSet",
      "com.google.common.base.Preconditions",
      "com.google.common.collect.UnmodifiableIterator",
      "com.google.common.collect.StandardTable$ColumnKeyIterator",
      "com.google.common.collect.ImmutableSortedSetFauxverideShim",
      "com.google.common.collect.ImmutableMapValues",
      "com.google.common.collect.Maps$FilteredEntryNavigableMap",
      "com.google.common.base.Converter$ConverterComposition",
      "com.google.common.collect.AbstractNavigableMap",
      "com.google.common.collect.ImmutableCollection",
      "com.google.common.collect.ImmutableEnumMap",
      "com.google.common.collect.Lists$RandomAccessListWrapper",
      "com.google.common.collect.ImmutableList$ReverseImmutableList",
      "com.google.escapevelocity.StopNode$ElseNode",
      "com.google.escapevelocity.StopNode$EofNode",
      "com.google.common.collect.SingletonImmutableList",
      "com.google.escapevelocity.ConstantExpressionNode",
      "com.google.common.base.Converter",
      "com.google.errorprone.annotations.DoNotMock",
      "com.google.common.collect.ImmutableCollection$Builder",
      "com.google.common.collect.ImmutableSet$JdkBackedSetBuilderImpl",
      "com.google.common.collect.ImmutableSetMultimap",
      "com.google.common.collect.Maps$8",
      "com.google.common.collect.BiMap",
      "com.google.common.collect.IndexedImmutableSet",
      "com.google.common.collect.ImmutableSet",
      "com.google.common.base.Function",
      "com.google.common.collect.Iterators$9",
      "com.google.common.collect.Lists$AbstractListWrapper",
      "com.google.escapevelocity.ReferenceNode$MethodReferenceNode",
      "com.google.common.collect.ImmutableMap",
      "com.google.common.collect.ComparatorOrdering",
      "com.google.common.collect.AbstractIndexedListIterator",
      "com.google.common.collect.ImmutableSortedAsList",
      "com.google.common.reflect.Reflection",
      "com.google.common.collect.CollectPreconditions",
      "com.google.common.collect.Iterators$1",
      "com.google.escapevelocity.StopNode$EndNode",
      "com.google.common.collect.Iterators$4",
      "com.google.common.collect.Iterators$5",
      "com.google.common.collect.ForwardingMap",
      "com.google.common.collect.StandardTable$ColumnMap",
      "com.google.escapevelocity.StopNode",
      "com.google.common.base.Converter$ReverseConverter",
      "com.google.escapevelocity.ExpressionNode",
      "com.google.common.collect.ExplicitOrdering",
      "com.google.common.collect.Lists$StringAsImmutableList",
      "com.google.common.collect.Maps$DescendingMap",
      "com.google.common.collect.Lists$2",
      "com.google.common.collect.Maps$ViewCachingAbstractMap",
      "com.google.common.collect.Maps$IteratorBasedAbstractMap",
      "com.google.common.collect.Maps$FilteredEntryBiMap",
      "com.google.escapevelocity.EvaluationException",
      "com.google.common.collect.ImmutableMap$1",
      "com.google.common.collect.Lists$1",
      "com.google.common.collect.ImmutableList$Builder",
      "com.google.common.collect.Maps$EntrySet",
      "com.google.common.collect.ForwardingObject",
      "com.google.common.collect.AbstractTable",
      "com.google.common.collect.AbstractMultimap",
      "com.google.common.base.Supplier",
      "com.google.common.collect.StandardTable$Column",
      "com.google.common.collect.Multimap",
      "com.google.common.collect.Iterators",
      "com.google.common.collect.CompoundOrdering",
      "com.google.common.collect.ImmutableBiMap",
      "com.google.common.collect.ImmutableList",
      "com.google.common.collect.ReverseOrdering",
      "com.google.common.collect.Table$Cell",
      "com.google.common.collect.ImmutableBiMapFauxverideShim",
      "com.google.common.collect.Maps$FilteredEntrySortedMap",
      "com.google.escapevelocity.ReferenceNode",
      "com.google.common.base.Equivalence",
      "com.google.common.collect.Iterators$PeekingImpl",
      "com.google.common.collect.ReverseNaturalOrdering",
      "com.google.common.collect.Maps",
      "com.google.common.collect.ImmutableMap$Builder",
      "com.google.common.base.Converter$FunctionBasedConverter",
      "com.google.common.collect.SetMultimap",
      "com.google.common.collect.Maps$EntryTransformer",
      "com.google.common.collect.ImmutableSet$RegularSetBuilderImpl",
      "com.google.common.collect.Ordering",
      "com.google.common.collect.NaturalOrdering",
      "com.google.common.collect.SortedIterables",
      "com.google.common.collect.Iterators$MergingIterator",
      "com.google.common.collect.RegularImmutableSortedSet",
      "com.google.common.collect.Table"
    );
  } 

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(MethodFinder_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.google.common.reflect.Reflection",
      "com.google.escapevelocity.MethodFinder",
      "com.google.common.collect.ImmutableCollection",
      "com.google.common.collect.ImmutableSet",
      "com.google.common.collect.RegularImmutableSet",
      "com.google.common.math.IntMath$1",
      "com.google.common.collect.AbstractTable",
      "com.google.common.collect.StandardTable",
      "com.google.common.collect.HashBasedTable",
      "com.google.common.collect.HashBasedTable$Factory",
      "com.google.common.collect.Maps$ViewCachingAbstractMap",
      "com.google.common.collect.StandardTable$RowMap",
      "com.google.common.collect.Maps",
      "com.google.common.base.Preconditions",
      "com.google.common.collect.Iterators",
      "com.google.common.collect.UnmodifiableIterator",
      "com.google.common.collect.UnmodifiableListIterator",
      "com.google.common.collect.AbstractIndexedListIterator",
      "com.google.common.collect.Iterators$ArrayItr",
      "com.google.common.collect.CollectPreconditions",
      "com.google.common.collect.Maps$IteratorBasedAbstractMap",
      "com.google.common.collect.StandardTable$Row",
      "com.google.common.collect.SingletonImmutableSet",
      "com.google.common.collect.ImmutableSet$SetBuilderImpl",
      "com.google.common.collect.ImmutableSet$RegularSetBuilderImpl",
      "com.google.common.math.IntMath",
      "com.google.common.math.MathPreconditions",
      "com.google.common.collect.Hashing",
      "com.google.escapevelocity.Node",
      "com.google.escapevelocity.StopNode",
      "com.google.escapevelocity.StopNode$EofNode",
      "com.google.common.collect.ImmutableSortedSetFauxverideShim",
      "com.google.common.collect.ImmutableSortedSet",
      "com.google.common.collect.SortedIterables",
      "com.google.common.collect.Iterables",
      "com.google.common.collect.Ordering",
      "com.google.common.collect.NaturalOrdering",
      "com.google.common.collect.ImmutableList",
      "com.google.common.collect.RegularImmutableList",
      "com.google.common.collect.RegularImmutableSortedSet"
    );
  }
}
