/**
 * Scaffolding file used to store all the setups needed to run 
 * tests automatically generated by EvoSuite
 * Thu Feb 27 18:35:15 GMT 2020
 */

package com.google.escapevelocity;

import org.evosuite.runtime.annotation.EvoSuiteClassExclude;
import org.junit.BeforeClass;
import org.junit.Before;
import org.junit.After;
import org.junit.AfterClass;
import org.evosuite.runtime.sandbox.Sandbox;
import org.evosuite.runtime.sandbox.Sandbox.SandboxMode;

import static org.evosuite.shaded.org.mockito.Mockito.*;
@EvoSuiteClassExclude
public class ReferenceNode_ESTest_scaffolding {

  @org.junit.Rule 
  public org.evosuite.runtime.vnet.NonFunctionalRequirementRule nfr = new org.evosuite.runtime.vnet.NonFunctionalRequirementRule();

  private static final java.util.Properties defaultProperties = (java.util.Properties) java.lang.System.getProperties().clone(); 

  private org.evosuite.runtime.thread.ThreadStopper threadStopper =  new org.evosuite.runtime.thread.ThreadStopper (org.evosuite.runtime.thread.KillSwitchHandler.getInstance(), 3000);


  @BeforeClass 
  public static void initEvoSuiteFramework() { 
    org.evosuite.runtime.RuntimeSettings.className = "com.google.escapevelocity.ReferenceNode"; 
    org.evosuite.runtime.GuiSupport.initialize(); 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfThreads = 100; 
    org.evosuite.runtime.RuntimeSettings.maxNumberOfIterationsPerLoop = 10000; 
    org.evosuite.runtime.RuntimeSettings.mockSystemIn = true; 
    org.evosuite.runtime.RuntimeSettings.sandboxMode = org.evosuite.runtime.sandbox.Sandbox.SandboxMode.RECOMMENDED; 
    org.evosuite.runtime.sandbox.Sandbox.initializeSecurityManagerForSUT(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.init();
    setSystemProperties();
    initializeClasses();
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    try { initMocksToAvoidTimeoutsInTheTests(); } catch(ClassNotFoundException e) {} 
  } 

  @AfterClass 
  public static void clearEvoSuiteFramework(){ 
    Sandbox.resetDefaultSecurityManager(); 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
  } 

  @Before 
  public void initTestCase(){ 
    threadStopper.storeCurrentThreads();
    threadStopper.startRecordingTime();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().initHandler(); 
    org.evosuite.runtime.sandbox.Sandbox.goingToExecuteSUTCode(); 
    setSystemProperties(); 
    org.evosuite.runtime.GuiSupport.setHeadless(); 
    org.evosuite.runtime.Runtime.getInstance().resetRuntime(); 
    org.evosuite.runtime.agent.InstrumentingAgent.activate(); 
  } 

  @After 
  public void doneWithTestCase(){ 
    threadStopper.killAndJoinClientThreads();
    org.evosuite.runtime.jvm.ShutdownHookHandler.getInstance().safeExecuteAddedHooks(); 
    org.evosuite.runtime.classhandling.JDKClassResetter.reset(); 
    resetClasses(); 
    org.evosuite.runtime.sandbox.Sandbox.doneWithExecutingSUTCode(); 
    org.evosuite.runtime.agent.InstrumentingAgent.deactivate(); 
    org.evosuite.runtime.GuiSupport.restoreHeadlessMode(); 
  } 

  public static void setSystemProperties() {
 
    java.lang.System.setProperties((java.util.Properties) defaultProperties.clone()); 
    java.lang.System.setProperty("file.encoding", "UTF-8"); 
    java.lang.System.setProperty("java.awt.headless", "true"); 
    java.lang.System.setProperty("java.io.tmpdir", "/var/folders/9c/2fm2fk412pj9zjkzvdx9w2fr0000gn/T/"); 
    java.lang.System.setProperty("user.country", "BR"); 
    java.lang.System.setProperty("user.dir", "/Users/joaocorreia/escapevelocity"); 
    java.lang.System.setProperty("user.home", "/Users/joaocorreia"); 
    java.lang.System.setProperty("user.language", "pt"); 
    java.lang.System.setProperty("user.name", "joaocorreia"); 
    java.lang.System.setProperty("user.timezone", "America/Sao_Paulo"); 
  }

  private static void initializeClasses() {
    org.evosuite.runtime.classhandling.ClassStateSupport.initializeClasses(ReferenceNode_ESTest_scaffolding.class.getClassLoader() ,
      "com.google.common.collect.Lists$RandomAccessPartition",
      "com.google.common.base.CharMatcher$ForPredicate",
      "com.google.common.collect.HashBasedTable",
      "com.google.common.collect.PeekingIterator",
      "com.google.common.hash.BloomFilter$Strategy",
      "com.google.escapevelocity.Macro",
      "com.google.common.collect.ImmutableSortedMap$1EntrySet",
      "com.google.common.collect.NullsLastOrdering",
      "com.google.common.collect.ImmutableMap$IteratorBasedImmutableMap$1EntrySetImpl",
      "com.google.common.collect.Platform",
      "com.google.escapevelocity.Node",
      "com.google.common.base.CharMatcher$JavaLetterOrDigit",
      "com.google.common.collect.ImmutableSortedMap$1",
      "com.google.common.collect.Maps$Values",
      "com.google.common.collect.RegularImmutableBiMap",
      "com.google.common.collect.RegularImmutableMap",
      "com.google.escapevelocity.MethodFinder",
      "com.google.common.collect.ImmutableMultimap$Values",
      "com.google.common.base.Converter$IdentityConverter",
      "com.google.common.collect.ByFunctionOrdering",
      "com.google.common.collect.Iterators$10",
      "com.google.common.collect.AbstractMapEntry",
      "com.google.common.collect.ImmutableMap$IteratorBasedImmutableMap",
      "com.google.common.collect.ImmutableBiMap$Builder",
      "com.google.common.base.Predicate",
      "com.google.common.base.CharMatcher$Invisible",
      "com.google.common.base.CharMatcher$None",
      "com.google.common.collect.Iterators$ConcatenatedIterator",
      "com.google.common.collect.HashBasedTable$Factory",
      "com.google.common.collect.NullsFirstOrdering",
      "com.google.common.base.Strings",
      "com.google.common.collect.Lists$Partition",
      "com.google.common.collect.Lists",
      "com.google.common.collect.UnmodifiableListIterator",
      "com.google.common.collect.DiscreteDomain",
      "com.google.common.collect.ImmutableMultimap",
      "com.google.common.collect.ImmutableSortedSet",
      "com.google.common.collect.Cut",
      "com.google.common.collect.Maps$BiMapConverter",
      "com.google.common.base.CharMatcher",
      "com.google.escapevelocity.Macro$MacroEvaluationContext",
      "com.google.common.collect.ImmutableSortedSet$Builder",
      "com.google.common.collect.StandardTable",
      "com.google.common.collect.Sets$ImprovedAbstractSet",
      "com.google.common.collect.ImmutableMapEntry$NonTerminalImmutableMapEntry",
      "com.google.common.base.Preconditions",
      "com.google.common.collect.ImmutableSortedSetFauxverideShim",
      "com.google.common.collect.MapMaker",
      "com.google.common.base.CharMatcher$1",
      "com.google.common.collect.ImmutableMapValues",
      "com.google.common.collect.ImmutableEntry",
      "com.google.common.base.CharMatcher$FastMatcher",
      "com.google.common.base.CharMatcher$JavaIsoControl",
      "com.google.common.base.Converter$ConverterComposition",
      "com.google.common.collect.EmptyImmutableSetMultimap",
      "com.google.common.collect.AbstractNavigableMap",
      "com.google.common.collect.ImmutableCollection",
      "com.google.common.collect.ImmutableEnumMap",
      "com.google.common.hash.BloomFilterStrategies",
      "com.google.common.base.CharMatcher$BitSetMatcher",
      "com.google.common.base.CharMatcher$JavaUpperCase",
      "com.google.common.collect.ImmutableSetMultimap",
      "com.google.common.collect.ImmutableCollection$Builder",
      "com.google.errorprone.annotations.DoNotMock",
      "com.google.common.collect.ImmutableSet$JdkBackedSetBuilderImpl",
      "com.google.common.collect.BiMap",
      "com.google.common.collect.IndexedImmutableSet",
      "com.google.common.collect.ImmutableSet",
      "com.google.common.collect.Iterators$9",
      "com.google.common.collect.Lists$AbstractListWrapper",
      "com.google.escapevelocity.ReferenceNode$MethodReferenceNode",
      "com.google.common.collect.ImmutableMapEntry",
      "com.google.escapevelocity.ReferenceNode$IndexReferenceNode",
      "com.google.common.collect.ImmutableSortedAsList",
      "com.google.common.reflect.Reflection",
      "com.google.common.base.CharMatcher$NamedFastMatcher",
      "com.google.common.collect.Iterators$1",
      "com.google.common.collect.Iterators$4",
      "com.google.common.collect.Iterators$5",
      "com.google.common.collect.StandardTable$ColumnMap",
      "com.google.common.collect.ImmutableMultimap$EntryCollection",
      "com.google.common.base.Converter$ReverseConverter",
      "com.google.escapevelocity.ExpressionNode",
      "com.google.common.collect.Lists$StringAsImmutableList",
      "com.google.common.base.CharMatcher$Is",
      "com.google.common.collect.Lists$2",
      "com.google.common.collect.Cut$AboveValue",
      "com.google.common.collect.Maps$IteratorBasedAbstractMap",
      "com.google.common.base.CharMatcher$SingleWidth",
      "com.google.common.collect.Maps$FilteredEntryBiMap",
      "com.google.common.collect.RegularImmutableBiMap$Inverse",
      "com.google.common.collect.Lists$1",
      "com.google.common.collect.Maps$EntrySet",
      "com.google.common.collect.ImmutableMultimap$Builder",
      "com.google.common.collect.Multiset",
      "com.google.common.collect.ImmutableSetMultimap$EntrySet",
      "com.google.common.collect.AbstractMultimap",
      "com.google.common.base.Supplier",
      "com.google.common.collect.ImmutableList",
      "com.google.common.collect.ReverseOrdering",
      "com.google.common.collect.Table$Cell",
      "com.google.escapevelocity.ExpressionNode$BinaryExpressionNode",
      "com.google.common.collect.ImmutableBiMapFauxverideShim",
      "com.google.common.collect.Maps$FilteredEntrySortedMap",
      "com.google.escapevelocity.ReferenceNode",
      "com.google.common.base.CharMatcher$Negated",
      "com.google.common.collect.Iterators$PeekingImpl",
      "com.google.common.hash.BloomFilter",
      "com.google.common.base.CharMatcher$Ascii",
      "com.google.common.collect.ImmutableMap$Builder",
      "com.google.common.base.Converter$FunctionBasedConverter",
      "com.google.common.collect.Maps$EntryTransformer",
      "com.google.common.collect.Ordering",
      "com.google.common.base.CharMatcher$Digit",
      "com.google.common.collect.NaturalOrdering",
      "com.google.common.collect.AllEqualOrdering",
      "com.google.common.collect.ImmutableSet$SetBuilderImpl",
      "com.google.common.collect.ImmutableMapEntrySet$EntrySetSerializedForm",
      "com.google.common.collect.Hashing",
      "com.google.common.collect.ImmutableList$SubList",
      "com.google.common.collect.ListMultimap",
      "com.google.common.base.CharMatcher$Whitespace",
      "com.google.common.collect.StandardTable$RowMap",
      "com.google.common.collect.ImmutableSortedMap$1EntrySet$1",
      "com.google.common.collect.ImmutableSortedMap$Builder",
      "com.google.common.collect.Maps$NavigableKeySet",
      "com.google.common.collect.RegularImmutableList",
      "com.google.common.collect.StandardTable$ColumnKeySet",
      "com.google.common.hash.BloomFilterStrategies$1",
      "com.google.escapevelocity.ReferenceNode$MemberReferenceNode",
      "com.google.common.hash.BloomFilterStrategies$2",
      "com.google.common.base.CharMatcher$JavaDigit",
      "com.google.escapevelocity.ReferenceNode$PlainReferenceNode",
      "com.google.common.base.Optional",
      "com.google.common.collect.Lists$TransformingRandomAccessList",
      "com.google.common.collect.RegularImmutableMap$KeySet",
      "com.google.common.collect.Iterators$ArrayItr",
      "com.google.escapevelocity.Node$Cons",
      "com.google.common.collect.Maps$KeySet",
      "com.google.common.base.CharMatcher$IsNot",
      "com.google.common.base.CharMatcher$JavaLetter",
      "com.google.common.base.CharMatcher$InRange",
      "com.google.common.collect.ImmutableMapKeySet",
      "com.google.common.collect.BaseImmutableMultimap",
      "com.google.common.base.CharMatcher$NegatedFastMatcher",
      "com.google.common.collect.Range",
      "com.google.common.collect.Maps$SortedKeySet",
      "com.google.common.collect.ImmutableMap$MapViewOfValuesAsSingletonSets$1",
      "com.google.common.collect.StandardTable$TableSet",
      "com.google.common.collect.SortedMapDifference",
      "com.google.common.collect.RegularImmutableSet",
      "com.google.common.hash.Funnel",
      "com.google.common.collect.LexicographicalOrdering",
      "com.google.common.base.CharMatcher$IsEither",
      "com.google.common.collect.ImmutableListMultimap",
      "com.google.common.collect.ImmutableMultimap$1",
      "com.google.common.collect.StandardTable$Row",
      "com.google.common.collect.Maps$AbstractFilteredMap",
      "com.google.escapevelocity.EvaluationContext",
      "com.google.common.collect.ImmutableMultimap$2",
      "com.google.common.collect.Iterables",
      "com.google.common.base.CharMatcher$Any",
      "com.google.common.collect.ImmutableAsList",
      "com.google.common.collect.ImmutableMapEntrySet$RegularEntrySet",
      "com.google.common.collect.ImmutableSet$Builder",
      "com.google.common.collect.RegularImmutableAsList",
      "com.google.common.collect.Maps$FilteredEntryMap",
      "com.google.common.collect.SingletonImmutableSet",
      "com.google.common.collect.Cut$BelowValue",
      "com.google.common.collect.ImmutableSetMultimap$Builder",
      "com.google.common.collect.ImmutableList$SerializedForm",
      "com.google.common.collect.ImmutableMapEntrySet",
      "com.google.escapevelocity.EvaluationContext$PlainEvaluationContext",
      "com.google.common.collect.ImmutableMultiset",
      "com.google.common.collect.UsingToStringOrdering",
      "com.google.common.collect.ImmutableMultimap$Keys",
      "com.google.common.collect.Maps$Accumulator",
      "com.google.common.collect.Lists$TransformingSequentialList",
      "com.google.common.collect.ImmutableSortedMap",
      "com.google.common.collect.RangeGwtSerializationDependencies",
      "com.google.common.collect.ObjectArrays",
      "com.google.common.collect.AbstractIterator",
      "com.google.common.collect.IndexedImmutableSet$1",
      "com.google.common.base.CharMatcher$And",
      "com.google.common.collect.ImmutableList$1",
      "com.google.common.collect.MapDifference",
      "com.google.common.collect.RegularImmutableBiMap$Inverse$InverseEntrySet",
      "com.google.common.collect.ImmutableMap$MapViewOfValuesAsSingletonSets",
      "com.google.common.collect.SortedIterable",
      "com.google.common.base.CharMatcher$AnyOf",
      "com.google.common.collect.UnmodifiableIterator",
      "com.google.common.collect.StandardTable$ColumnKeyIterator",
      "com.google.common.collect.Maps$FilteredEntryNavigableMap",
      "com.google.escapevelocity.ExpressionNode$NotExpressionNode",
      "com.google.common.collect.Lists$RandomAccessListWrapper",
      "com.google.common.collect.ImmutableList$ReverseImmutableList",
      "com.google.common.collect.ImmutableMultisetGwtSerializationDependencies",
      "com.google.common.base.CharMatcher$RangesMatcher",
      "com.google.common.collect.SingletonImmutableList",
      "com.google.common.base.Converter",
      "com.google.escapevelocity.ConstantExpressionNode",
      "com.google.common.collect.Maps$8",
      "com.google.common.base.Function",
      "com.google.common.base.CharMatcher$BreakingWhitespace",
      "com.google.common.collect.ImmutableMap",
      "com.google.common.collect.ComparatorOrdering",
      "com.google.common.collect.AbstractIndexedListIterator",
      "com.google.common.collect.CollectPreconditions",
      "com.google.common.collect.ImmutableSortedMapFauxverideShim",
      "com.google.common.collect.ForwardingMap",
      "com.google.common.collect.BoundType",
      "com.google.common.collect.ExplicitOrdering",
      "com.google.common.collect.Maps$DescendingMap",
      "com.google.common.collect.Maps$ViewCachingAbstractMap",
      "com.google.common.base.CharMatcher$JavaLowerCase",
      "com.google.escapevelocity.EvaluationException",
      "com.google.common.collect.ImmutableMap$1",
      "com.google.common.collect.ImmutableList$Builder",
      "com.google.common.primitives.Booleans",
      "com.google.common.collect.ForwardingObject",
      "com.google.common.collect.AbstractTable",
      "com.google.common.collect.StandardTable$Column",
      "com.google.common.collect.ImmutableMapEntry$NonTerminalImmutableBiMapEntry",
      "com.google.common.collect.Multimap",
      "com.google.common.collect.CompoundOrdering",
      "com.google.common.collect.Iterators",
      "com.google.common.collect.ImmutableBiMap",
      "com.google.common.collect.SingletonImmutableBiMap",
      "com.google.common.collect.Ordering$IncomparableValueException",
      "com.google.common.hash.BloomFilterStrategies$LockFreeBitArray",
      "com.google.common.base.Equivalence",
      "com.google.common.collect.Cut$BelowAll",
      "com.google.common.collect.ReverseNaturalOrdering",
      "com.google.common.collect.Maps",
      "com.google.common.collect.SetMultimap",
      "com.google.common.base.CharMatcher$Or",
      "com.google.common.primitives.Primitives",
      "com.google.common.collect.ImmutableSet$RegularSetBuilderImpl",
      "com.google.common.collect.Iterators$MergingIterator",
      "com.google.common.collect.RegularImmutableMap$Values",
      "com.google.common.collect.RegularImmutableSortedSet",
      "com.google.common.collect.Cut$AboveAll",
      "com.google.common.collect.Table"
    );
  } 
  private static void initMocksToAvoidTimeoutsInTheTests() throws ClassNotFoundException { 
    mock(Class.forName("java.util.Comparator", false, ReferenceNode_ESTest_scaffolding.class.getClassLoader()));
  }

  private static void resetClasses() {
    org.evosuite.runtime.classhandling.ClassResetter.getInstance().setClassLoader(ReferenceNode_ESTest_scaffolding.class.getClassLoader()); 

    org.evosuite.runtime.classhandling.ClassStateSupport.resetClasses(
      "com.google.escapevelocity.Node",
      "com.google.escapevelocity.ExpressionNode",
      "com.google.escapevelocity.ReferenceNode",
      "com.google.escapevelocity.ReferenceNode$PlainReferenceNode",
      "com.google.escapevelocity.ReferenceNode$IndexReferenceNode",
      "com.google.common.collect.ImmutableCollection",
      "com.google.common.collect.ImmutableList",
      "com.google.common.collect.ObjectArrays",
      "com.google.common.collect.RegularImmutableList",
      "com.google.common.collect.Lists",
      "com.google.escapevelocity.ReferenceNode$MethodReferenceNode",
      "com.google.common.collect.ImmutableMap",
      "com.google.common.collect.CollectPreconditions",
      "com.google.common.collect.RegularImmutableMap",
      "com.google.common.base.Preconditions",
      "com.google.common.collect.Hashing",
      "com.google.common.collect.AbstractMapEntry",
      "com.google.common.collect.ImmutableEntry",
      "com.google.common.collect.ImmutableMapEntry",
      "com.google.common.collect.ImmutableMapEntry$NonTerminalImmutableMapEntry",
      "com.google.escapevelocity.ReferenceNode$MemberReferenceNode",
      "com.google.escapevelocity.EvaluationException",
      "com.google.escapevelocity.Node$Cons",
      "com.google.escapevelocity.Macro$MacroEvaluationContext",
      "com.google.common.collect.ImmutableBiMapFauxverideShim",
      "com.google.common.collect.ImmutableBiMap",
      "com.google.escapevelocity.ExpressionNode$NotExpressionNode",
      "com.google.common.collect.RegularImmutableBiMap",
      "com.google.common.reflect.Reflection",
      "com.google.escapevelocity.MethodFinder",
      "com.google.common.collect.AbstractTable",
      "com.google.common.collect.StandardTable",
      "com.google.common.collect.HashBasedTable",
      "com.google.common.collect.HashBasedTable$Factory",
      "com.google.escapevelocity.EvaluationContext$PlainEvaluationContext",
      "com.google.common.collect.SingletonImmutableBiMap",
      "com.google.common.collect.ImmutableSortedMapFauxverideShim",
      "com.google.common.collect.Ordering",
      "com.google.common.collect.NaturalOrdering",
      "com.google.common.collect.ImmutableSet",
      "com.google.common.collect.ImmutableSortedSetFauxverideShim",
      "com.google.common.collect.ImmutableSortedSet",
      "com.google.common.collect.RegularImmutableSortedSet",
      "com.google.common.collect.ImmutableSortedMap",
      "com.google.escapevelocity.ConstantExpressionNode",
      "com.google.common.collect.Iterables",
      "com.google.common.collect.RegularImmutableSet",
      "com.google.common.collect.Iterators",
      "com.google.common.collect.UnmodifiableIterator",
      "com.google.common.collect.UnmodifiableListIterator",
      "com.google.common.collect.AbstractIndexedListIterator",
      "com.google.common.collect.Iterators$ArrayItr",
      "com.google.common.base.Strings",
      "com.google.common.collect.ImmutableSortedMap$1",
      "com.google.common.collect.ImmutableMapEntrySet",
      "com.google.common.collect.ImmutableSortedMap$1EntrySet",
      "com.google.common.collect.ImmutableAsList",
      "com.google.common.collect.ImmutableSortedMap$1EntrySet$1",
      "com.google.common.collect.ImmutableList$1",
      "com.google.common.collect.RegularImmutableAsList",
      "com.google.common.collect.ImmutableSortedAsList",
      "com.google.escapevelocity.ExpressionNode$BinaryExpressionNode",
      "com.google.common.collect.SingletonImmutableList",
      "com.google.common.collect.Maps$ViewCachingAbstractMap",
      "com.google.common.collect.StandardTable$RowMap",
      "com.google.common.collect.Maps",
      "com.google.common.hash.BloomFilter",
      "com.google.common.hash.BloomFilterStrategies",
      "com.google.common.collect.ImmutableMapEntrySet$RegularEntrySet",
      "com.google.common.collect.Platform",
      "com.google.common.collect.SingletonImmutableSet",
      "com.google.common.collect.Iterators$9",
      "com.google.common.collect.ImmutableCollection$Builder",
      "com.google.common.collect.ImmutableList$Builder",
      "com.google.common.collect.ImmutableMapEntry$NonTerminalImmutableBiMapEntry",
      "com.google.common.collect.RangeGwtSerializationDependencies",
      "com.google.common.collect.Cut",
      "com.google.common.collect.Cut$BelowAll",
      "com.google.common.collect.Cut$AboveAll",
      "com.google.common.collect.Range",
      "com.google.common.collect.ImmutableList$ReverseImmutableList",
      "com.google.common.collect.ReverseNaturalOrdering",
      "com.google.common.collect.Cut$AboveValue",
      "com.google.common.collect.Cut$BelowValue",
      "com.google.common.base.CharMatcher",
      "com.google.common.base.CharMatcher$FastMatcher",
      "com.google.common.base.CharMatcher$NamedFastMatcher",
      "com.google.common.base.CharMatcher$Whitespace",
      "com.google.common.collect.AbstractMultimap",
      "com.google.common.collect.BaseImmutableMultimap",
      "com.google.common.collect.ImmutableMultimap",
      "com.google.common.collect.ImmutableSetMultimap",
      "com.google.common.collect.EmptyImmutableSetMultimap",
      "com.google.common.collect.Maps$IteratorBasedAbstractMap",
      "com.google.common.collect.StandardTable$Row",
      "com.google.common.primitives.Booleans",
      "com.google.common.primitives.Primitives"
    );
  }
}
